import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { CheckCircle2, User } from "lucide-react";
import { Navbar, Footer } from "@/components/SiteChrome";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";

type Profile = Tables<"profiles">;
const emptyProfile = { display_name: "", username: "", headline: "", bio: "", location: "", college_or_company: "", skills: "", interests: "", github_url: "", linkedin_url: "", website_url: "" };

export const Route = createFileRoute("/_authenticated/profile")({
  head: () => ({ meta: [{ title: "Builder Profile — Vybe Driven" }, { name: "description", content: "Complete and manage your private Vybe Driven builder profile." }, { property: "og:title", content: "Builder Profile — Vybe Driven" }, { property: "og:description", content: "Build your identity in the Vybe Driven community." }, { property: "og:type", content: "profile" }, { name: "twitter:card", content: "summary" }] }),
  component: ProfilePage,
});

function ProfilePage() {
  const { user } = Route.useRouteContext();
  const [form, setForm] = useState(emptyProfile); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { supabase.from("profiles").select("*").eq("id", user.id).maybeSingle().then(({ data }) => { const profile = data as Profile | null; if (profile) setForm({ display_name: profile.display_name, username: profile.username ?? "", headline: profile.headline, bio: profile.bio, location: profile.location, college_or_company: profile.college_or_company, skills: profile.skills.join(", "), interests: profile.interests.join(", "), github_url: profile.github_url ?? "", linkedin_url: profile.linkedin_url ?? "", website_url: profile.website_url ?? "" }); else setForm((value) => ({ ...value, display_name: String(user.user_metadata?.["full_name"] ?? "") })); setLoading(false); }); }, [user]);
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setMessage(""); const complete = Boolean(form.display_name && form.headline && form.location && form.skills); const { error: saveError } = await supabase.from("profiles").upsert({ id: user.id, display_name: form.display_name, username: form.username || null, headline: form.headline, bio: form.bio, location: form.location, college_or_company: form.college_or_company, skills: form.skills.split(",").map((item) => item.trim()).filter(Boolean), interests: form.interests.split(",").map((item) => item.trim()).filter(Boolean), github_url: form.github_url || null, linkedin_url: form.linkedin_url || null, website_url: form.website_url || null, profile_complete: complete, updated_at: new Date().toISOString() }); setSaving(false); if (saveError) setError(saveError.message); else setMessage(complete ? "Profile complete and saved." : "Progress saved. Add the highlighted essentials when you’re ready."); };
  const field = (label: string, key: keyof typeof form, placeholder: string, required = false) => <label className="block text-sm font-medium">{label}{required && <span className="text-neon"> *</span>}<input required={required} value={form[key]} onChange={(event) => set(key, event.target.value)} placeholder={placeholder} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-4 outline-none focus:ring-2 focus:ring-ring" /></label>;
  if (loading) return <div className="min-h-screen"><Navbar /><div className="mx-auto max-w-[1000px] px-6 py-24 text-muted-foreground">Loading your profile…</div></div>;
  return <div className="min-h-screen"><Navbar /><main className="mx-auto max-w-[1000px] px-6 py-14"><div className="flex flex-col gap-5 border-b border-border pb-8 sm:flex-row sm:items-center"><span className="grid size-16 place-items-center rounded-full bg-neon/15 text-neon"><User className="size-7" /></span><div><p className="text-xs font-semibold tracking-[0.2em] text-neon">BUILDER PROFILE</p><h1 className="mt-2 text-3xl font-bold">Tell the community what you build.</h1><p className="mt-2 text-sm text-muted-foreground">Your essentials help future teammates understand where you fit.</p></div></div><form onSubmit={save} className="mt-8 space-y-8"><section><h2 className="text-lg font-bold">Essentials</h2><div className="mt-4 grid gap-5 sm:grid-cols-2">{field("Display name", "display_name", "Ada Lovelace", true)}{field("Username", "username", "ada-builds")}{field("Headline", "headline", "AI engineer and product builder", true)}{field("Location", "location", "Bengaluru", true)}{field("College or company", "college_or_company", "Your organization")}{field("Skills", "skills", "React, Python, Product", true)}</div><label className="mt-5 block text-sm font-medium">Bio<textarea value={form.bio} onChange={(event) => set("bio", event.target.value)} placeholder="What do you care about building?" className="mt-2 min-h-28 w-full resize-y rounded-xl border border-input bg-background p-4 outline-none focus:ring-2 focus:ring-ring" /></label>{field("Interests", "interests", "Climate tech, AI, Open source")}</section><section className="border-t border-border pt-8"><h2 className="text-lg font-bold">Links</h2><div className="mt-4 grid gap-5 sm:grid-cols-3">{field("GitHub", "github_url", "https://github.com/...")}{field("LinkedIn", "linkedin_url", "https://linkedin.com/in/...")}{field("Website", "website_url", "https://...")}</div></section>{error && <p className="text-sm text-destructive">{error}</p>}{message && <p className="flex items-center gap-2 text-sm text-neon"><CheckCircle2 className="size-4" />{message}</p>}<Button disabled={saving} className="h-11 rounded-xl bg-gradient-brand px-7 text-primary-foreground">{saving ? "Saving…" : "Save profile"}</Button></form></main><Footer /></div>;
}